### ISSUE TITLE
infinite loading

### ISSUE THREAD

**Issue by ahmedezz012** [gmatyszczak/screen-generator-plugin#16]
when i click on screen generator plugin i got the following screen shot
[
![plugin](https://user-images.githubusercontent.com/23040105/114431991-6f675080-9bc0-11eb-9977-6337057c7824.png)
](url)

**Comment by gmatyszczak** [comment]
Hi @ahmedezz012, what's your Android Studio version? And probably there's some error in IDE error log (red icon in bottom right corner), could you paste it here too?

**Comment by ahmedezz012** [comment]
> Hi @ahmedezz012, what's your Android Studio version? And probably there's some error in IDE error log (red icon in bottom right corner), could you paste it here too?

Hi @gmatyszczak, the android studio version is 4.1.2 and i update it to 4.1.3 and same issue happened. and i haven't errors in the ide error log

**Comment by panq-jack** [comment]
keep showing loading icon in Android Stuidio 4.1.x and 4.2.2

**Comment by panq-jack** [comment]
I got the error logs when open plugin setting or click 'Screen' in file menu, 
it says cannot find dagger.
however I add dagger dependency in target android studio project, same error.
anybody also face this issue?

java.lang.NoClassDefFoundError: dagger/internal/Preconditions
	at ui.newscreen.dagger.DaggerNewScreenComponent$Factory.create(DaggerNewScreenComponent.java:131)
	at ui.newscreen.NewScreenDialog.<init>(NewScreenDialog.kt:34)
	at ui.newscreen.NewScreenAnAction.actionPerformed(NewScreenAnAction.kt:18)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)

**Comment by gmatyszczak** [comment]
@panq-jack Which Android Studio version are you using? Did you install the plugin from Marketplace or you built it from source?

**Comment by gmatyszczak** [comment]
Fixed in [v1.2.2](https://github.com/gmatyszczak/screen-generator-plugin/releases/tag/v1.2.2)
